<?php
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_66ae6759476b1',
	'title' => 'Hello Pricing Plan Levels',
	'fields' => array(
		array(
			'key' => 'field_66ae67594cde0',
			'label' => 'Hello Pricing Plan Step 1',
			'name' => 'hello_pricing_plan_step_1',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key' => 'field_66ae675956c8c',
					'label' => 'Step Challenge',
					'name' => 'pt_step_challenge_name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'Step Challenge Name',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675956cc2',
					'label' => 'Starting Funded Balance',
					'name' => 'pt_starting_funded_balance',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675956cf7',
					'label' => 'Max Capital Growth',
					'name' => 'pt_max_capital_growth',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675956d2d',
					'label' => 'Account Scaling Target',
					'name' => 'pt_account_scaling_target',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675956d62',
					'label' => 'News Trading',
					'name' => 'pt_news_trading',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675956d96',
					'label' => 'Virtual Profit Share',
					'name' => 'pt_virtual_profit_share',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675956dcb',
					'label' => 'Daily Drawdown',
					'name' => 'pt_daily_drawdown',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675956e00',
					'label' => 'Total Drawdown',
					'name' => 'pt_total_drawdown',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675956e35',
					'label' => 'Payout Target',
					'name' => 'pt_payout_target',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_66ae67594ce18',
			'label' => 'Hello Pricing Plan Step 2',
			'name' => 'hello_pricing_plan_step_2',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key' => 'field_66ae675960c4b',
					'label' => 'Step Challenge',
					'name' => 'pt_step_challenge_name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'Step Challenge Name',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675960c81',
					'label' => 'Starting Funded Balance',
					'name' => 'pt_starting_funded_balance',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675960cb6',
					'label' => 'Max Capital Growth',
					'name' => 'pt_max_capital_growth',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675960ceb',
					'label' => 'Account Scaling Target',
					'name' => 'pt_account_scaling_target',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675960d20',
					'label' => 'News Trading',
					'name' => 'pt_news_trading',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675960d55',
					'label' => 'Virtual Profit Share',
					'name' => 'pt_virtual_profit_share',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675960d8a',
					'label' => 'Daily Drawdown',
					'name' => 'pt_daily_drawdown',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675960dbf',
					'label' => 'Total Drawdown',
					'name' => 'pt_total_drawdown',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675960df4',
					'label' => 'Payout Target',
					'name' => 'pt_payout_target',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_66ae67594ce4f',
			'label' => 'Hello Pricing Plan Step 3',
			'name' => 'hello_pricing_plan_step_3',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key' => 'field_66ae675967b8f',
					'label' => 'Step Challenge',
					'name' => 'pt_step_challenge_name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'Step Challenge Name',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675967bc5',
					'label' => 'Starting Funded Balance',
					'name' => 'pt_starting_funded_balance',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675967bfa',
					'label' => 'Max Capital Growth',
					'name' => 'pt_max_capital_growth',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675967c2f',
					'label' => 'Account Scaling Target',
					'name' => 'pt_account_scaling_target',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675967c64',
					'label' => 'News Trading',
					'name' => 'pt_news_trading',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675967c99',
					'label' => 'Virtual Profit Share',
					'name' => 'pt_virtual_profit_share',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675967cce',
					'label' => 'Daily Drawdown',
					'name' => 'pt_daily_drawdown',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675967d03',
					'label' => 'Total Drawdown',
					'name' => 'pt_total_drawdown',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66ae675967d38',
					'label' => 'Payout Target',
					'name' => 'pt_payout_target',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'product',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Hello Pricing Plans',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_669f6e7b62f3f',
	'title' => 'Hello Pricing Plan Tooltips',
	'fields' => array(
		array(
			'key' => 'field_669f6e7b69c7f',
			'label' => 'Hello Pricing Plan Tooltips',
			'name' => 'hello_pricing_plan_tooltips',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_669f6e7b6d9a7',
					'label' => 'Starting Funded Balance',
					'name' => 'pt_starting_funded_balance',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_669f6e7b6d9e6',
					'label' => 'Max Capital Growth',
					'name' => 'pt_max_capital_growth',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_669f6e7b6da25',
					'label' => 'Account Scaling Target',
					'name' => 'pt_account_scaling_target',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_669f6e7b6da65',
					'label' => 'News Trading',
					'name' => 'pt_news_trading',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_669f6e7b6daa4',
					'label' => 'Virtual Profit Share',
					'name' => 'pt_virtual_profit_share',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_669f6e7b6dae2',
					'label' => 'Daily Drawdown',
					'name' => 'pt_daily_drawdown',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_669f6e7b6db02',
					'label' => 'Total Drawdown',
					'name' => 'pt_total_drawdown',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_669f6e7b6db41',
					'label' => 'Payout Target',
					'name' => 'pt_payout_target',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'hello-tooltip',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Hello Pricing Plan Tooltips',
	'show_in_rest' => 0,
) );
} );

add_action( 'init', function() {
	register_post_type( 'hello-tooltip', array(
	'labels' => array(
		'name' => 'Hello Tooltips',
		'singular_name' => 'Hello Tooltip',
		'menu_name' => 'Hello Tooltips',
		'all_items' => 'All Hello Tooltips',
		'edit_item' => 'Edit Hello Tooltip',
		'view_item' => 'View Hello Tooltip',
		'view_items' => 'View Hello Tooltips',
		'add_new_item' => 'Add New Hello Tooltip',
		'add_new' => 'Add New Hello Tooltip',
		'new_item' => 'New Hello Tooltip',
		'parent_item_colon' => 'Parent Hello Tooltip:',
		'search_items' => 'Search Hello Tooltips',
		'not_found' => 'No hello tooltips found',
		'not_found_in_trash' => 'No hello tooltips found in Trash',
		'archives' => 'Hello Tooltip Archives',
		'attributes' => 'Hello Tooltip Attributes',
		'insert_into_item' => 'Insert into hello tooltip',
		'uploaded_to_this_item' => 'Uploaded to this hello tooltip',
		'filter_items_list' => 'Filter hello tooltips list',
		'filter_by_date' => 'Filter hello tooltips by date',
		'items_list_navigation' => 'Hello Tooltips list navigation',
		'items_list' => 'Hello Tooltips list',
		'item_published' => 'Hello Tooltip published.',
		'item_published_privately' => 'Hello Tooltip published privately.',
		'item_reverted_to_draft' => 'Hello Tooltip reverted to draft.',
		'item_scheduled' => 'Hello Tooltip scheduled.',
		'item_updated' => 'Hello Tooltip updated.',
		'item_link' => 'Hello Tooltip Link',
		'item_link_description' => 'A link to a hello tooltip.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_position' => 3,
	'menu_icon' => 'dashicons-screenoptions',
	'supports' => array(
		0 => 'title',
		1 => 'custom-fields',
	),
	'delete_with_user' => false,
) );
} );
?>